Add connection timeout & increase resilience
lsd-consulting/lsd-distributed-mongodb-access pull request #4
Opened 2021-11-22 22:39 UTC by lukasz-gryzbon

2021-11-23 22:32 UTC, nickmcdowall commented on src/main/java/io/lsdconsulting/lsd/distributed/mongo/config/LibraryConfig.java
> +        return new InterceptedDocumentMongoRepository(dbConnectionString, trustStoreLocation, trustStorePassword, connectionTimeout);
very useful addition 👍

2021-11-23 22:40 UTC, nickmcdowall commented on src/test/java/io/lsdconsulting/lsd/distributed/mongo/integration/InterceptedDocumentMongoRepositoryResiliencyIT.java
> +    }
fyi I'm getting a failure locally for this test with this error:

`Condition was evaluated in 112 milliseconds which is earlier than expected minimum timeout 450 milliseconds`
due to the condition:
```
await()
    .atLeast(450, MILLISECONDS)
```

Could we remove the atLeast or will we lose some confidence?

2021-11-23 22:42 UTC, nickmcdowall requested changes
Really useful additions to give confidence when running against systems outside dev 👍

Just noticed an issue locally with one of the tests - details in the PR comments.

Thanks for looking into the resilience 👏

2021-11-25 21:30 UTC, nickmcdowall commented on src/test/java/io/lsdconsulting/lsd/distributed/mongo/integration/InterceptedDocumentMongoRepositoryResiliencyIT.java
> +    }
Hey - not sure test is doing what it was expected to do?

For me It seems to timeout before the repository constructor finishes i.e. in `new InterceptedDocumentMongoRepository(...` resulting in the database being in a disabled state so the next steps are quick i.e. these steps then don't do anything because they drop into the catch blocks.

```
        underTest.save(interceptedInteraction);
        tearDownDatabase();
```

Can you check if you are seeing the same on your machine?

2021-11-30 22:03 UTC, lukasz-gryzbon commented on src/test/java/io/lsdconsulting/lsd/distributed/mongo/integration/InterceptedDocumentMongoRepositoryResiliencyIT.java
> +    }
The only think I could think of is - could you check if you have a MongoDB instance running, eg. in Docker while running these tests? This is the only think that would explain why this fails quicker than 500 ms. But also it would fail with an authorisation error....

2021-12-02 10:48 UTC, lukasz-gryzbon commented
Closing this PR for now. We can always revisit the failing test issue.

2021-12-02 10:48 UTC, closed without merging